language: c

compiler:
- gcc

before_install:
- echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
- sudo apt-get update -qq

install:
- sudo apt-get install cmake
- sudo apt-get install check

before_script:
- mkdir build
- cd build

script:
- cmake ..
- make
- cd tests
- ctest --output-on-failure .
